lang: en-US
title: My Awesome Site
# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
# plugins: # previsously gems
  # - jekyll-feed
  # - jekyll-seo-tag
  # - jekyll-sitemap
  # - jekyll-paginate
# feed:
#   path: atom.xml

# # Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/


# Front Matter Defaults
# defaults:
#   # _posts
#   - scope:
#       path: "_posts"
#       type: posts
#     values:
#       layout: post
#       read_time: true
#       theme: jekyll-theme-minimal

# remote_theme: pages-themes/cayman@v0.2.0
# cayman , time-machine
# title: My GitHub Page
# description: A simple Jekyll theme for GitHub Pages

